export enum Currency {
  USD = "USD",
  USDC = "USDC",
  USDT = "USDT",
  ETH = "ETH",
  BTC = "BTC",
  SOL = "SOL",
  ARB = "ARB",
  BNB = "BNB",
  ZK = "ZK",
  POL = "POL",
  OP = "OP",
  ATOM = "ATOM",
  KPEPE = "KPEPE",
  TON = "TON",
  XRP = "XRP",
  XLM = "XLM",
  WLD = "WLD",
  WIF = "WIF",
  VIRTUAL = "VIRTUAL",
  TRUMP = "TRUMP",
  SUI = "SUI",
  KSHIB = "KSHIB",
  POPCAT = "POPCAT",
  PENGU = "PENGU",
  LINK = "LINK",
  KBONK = "KBONK",
  JUP = "JUP",
  FARTCOIN = "FARTCOIN",
  ENA = "ENA",
  DOGE = "DOGE",
  AIXBT = "AIXBT",
  AI16Z = "AI16Z",
  ADA = "ADA",
  AAVE = "AAVE",
  BERA = "BERA",
  VINE = "VINE",
  PENDLE = "PENDLE",
  UXLINK = "UXLINK",
}

export enum TimeInForce {
  GOOD_TILL_TIME = "GOOD_TILL_TIME",
  ALL_OR_NONE = "ALL_OR_NONE",
  IMMEDIATE_OR_CANCEL = "IMMEDIATE_OR_CANCEL",
  FILL_OR_KILL = "FILL_OR_KILL",
}

export enum OrderStatus {
  PENDING = "PENDING",
  OPEN = "OPEN",
  FILLED = "FILLED",
  REJECTED = "REJECTED",
  CANCELLED = "CANCELLED",
}

export enum OrderRejectReason {
  UNSPECIFIED = "UNSPECIFIED",
  CLIENT_CANCEL = "CLIENT_CANCEL",
  CLIENT_BULK_CANCEL = "CLIENT_BULK_CANCEL",
  CLIENT_SESSION_END = "CLIENT_SESSION_END",
  MARKET_CANCEL = "MARKET_CANCEL",
  IOC_CANCEL = "IOC_CANCEL",
  AON_CANCEL = "AON_CANCEL",
  FOK_CANCEL = "FOK_CANCEL",
  EXPIRED = "EXPIRED",
  FAIL_POST_ONLY = "FAIL_POST_ONLY",
  FAIL_REDUCE_ONLY = "FAIL_REDUCE_ONLY",
  MM_PROTECTION = "MM_PROTECTION",
  SELF_TRADE_PROTECTION = "SELF_TRADE_PROTECTION",
  SELF_MATCHED_SUBACCOUNT = "SELF_MATCHED_SUBACCOUNT",
  OVERLAPPING_CLIENT_ORDER_ID = "OVERLAPPING_CLIENT_ORDER_ID",
  BELOW_MARGIN = "BELOW_MARGIN",
  LIQUIDATION = "LIQUIDATION",
  INSTRUMENT_INVALID = "INSTRUMENT_INVALID",
  INSTRUMENT_DEACTIVATED = "INSTRUMENT_DEACTIVATED",
  SYSTEM_FAILOVER = "SYSTEM_FAILOVER",
  UNAUTHORISED = "UNAUTHORISED",
  SESSION_KEY_EXPIRED = "SESSION_KEY_EXPIRED",
  SUB_ACCOUNT_NOT_FOUND = "SUB_ACCOUNT_NOT_FOUND",
  NO_TRADE_PERMISSION = "NO_TRADE_PERMISSION",
  UNSUPPORTED_TIME_IN_FORCE = "UNSUPPORTED_TIME_IN_FORCE",
  MULTI_LEGGED_ORDER = "MULTI_LEGGED_ORDER",
  EXCEED_MAX_POSITION_SIZE = "EXCEED_MAX_POSITION_SIZE",
  EXCEED_MAX_SIGNATURE_EXPIRATION = "EXCEED_MAX_SIGNATURE_EXPIRATION",
  MARKET_ORDER_WITH_LIMIT_PRICE = "MARKET_ORDER_WITH_LIMIT_PRICE",
  CLIENT_CANCEL_ON_DISCONNECT_TRIGGERED = "CLIENT_CANCEL_ON_DISCONNECT_TRIGGERED",
  OCO_COUNTER_PART_TRIGGERED = "OCO_COUNTER_PART_TRIGGERED",
}

export enum TransferType {
  STANDARD = "STANDARD",
  FAST_ARB_DEPOSIT = "FAST_ARB_DEPOSIT",
  FAST_ARB_WITHDRAWAL = "FAST_ARB_WITHDRAWAL",
}

export enum Kind {
  PERPETUAL = "PERPETUAL",
  FUTURE = "FUTURE",
  CALL = "CALL",
  PUT = "PUT",
}

export enum MarginType {
  SIMPLE_CROSS_MARGIN = "SIMPLE_CROSS_MARGIN",
  PORTFOLIO_CROSS_MARGIN = "PORTFOLIO_CROSS_MARGIN",
}

export enum TriggerBy {
  UNSPECIFIED = "UNSPECIFIED",
  INDEX = "INDEX",
  LAST = "LAST",
}

export enum TriggerType {
  UNSPECIFIED = "UNSPECIFIED",
  TAKE_PROFIT = "TAKE_PROFIT",
  STOP_LOSS = "STOP_LOSS",
}

export enum Venue {
  ORDERBOOK = "ORDERBOOK",
  RFQ = "RFQ",
}
